config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments, only: [:index]
  end

  get 'posts/new/:variable_x/:variable_y', controller: 'posts', action: 'new'

  root 'formularios#formularios'
  post 'formularios/formularios'
  get  'formularios/formularios'
  post 'formularios/formularios_rails'
  get  'formularios/formularios_rails'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/post_1.rb
class Post1 < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.where(post_id: params[:post_id])
  end
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController

  def formularios
    @uno = User.new
  end

  def formularios_post
    missings = missing_fields
    if missings.count > 0
      redirect_to formularios_formularios_path, alert: msg(missings)
    else
      @user = User.create(name: params[:user][:name], age: params[:user][:age], address: params[:user][:address])
      redirect_to formularios_formularios_path, alert: 'Bien guardado'
    end
  end

  private

  def msg(missings)
    msg = 'No pude guardar me falta algo '
    missings.each do |missing|
      msg << "#{missing} "
    end
    msg
  end

  def missing_fields
    missings = []
    requireds.each do |required|
      if params[:user][required] == ''
        missings << required
      end
    end
    missings
  end

  def requireds
    [:campo1, :campo2, :campo3, :campo4, :campo5, :campo6, :campo7, :campo8, :campo9]
  end
end

app/controllers/post_1s_controller.rb
class Post1sController < ApplicationController
  before_action :set_post_1, only: [:show, :edit, :update, :destroy]

  # GET /post_1s
  # GET /post_1s.json
  def index
    @post_1s = Post1.all
  end

  # GET /post_1s/1
  # GET /post_1s/1.json
  def show
  end

  # GET /post_1s/new
  def new
    @post_1 = Post1.new
  end

  # GET /post_1s/1/edit
  def edit
  end

  # POST /post_1s
  # POST /post_1s.json
  def create
    @post_1 = Post1.new(post_1_params)

    respond_to do |format|
      if @post_1.save
        format.html { redirect_to @post_1, notice: 'Post 1 was successfully created.' }
        format.json { render :show, status: :created, location: @post_1 }
      else
        format.html { render :new }
        format.json { render json: @post_1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_1s/1
  # PATCH/PUT /post_1s/1.json
  def update
    respond_to do |format|
      if @post_1.update(post_1_params)
        format.html { redirect_to @post_1, notice: 'Post 1 was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_1 }
      else
        format.html { render :edit }
        format.json { render json: @post_1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_1s/1
  # DELETE /post_1s/1.json
  def destroy
    @post_1.destroy
    respond_to do |format|
      format.html { redirect_to post_1s_url, notice: 'Post 1 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_1
      @post_1 = Post1.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_1_params
      params.require(:post_1).permit(:title, :content, :age)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :age, :agree)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/post_1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>Listado de Comentarios del Post de titulo <%= @post.title %></h1>
<table>
  <thead>
    <th>Contenido<th>
  </thead>
  <tbody>
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= params %>

app/views/formularios/formularios.html.erb
<%= flash[:alert] %>
<%= form_for(@uno, url: formularios_formularios_post_path, method: "post") do |f| %>
  <label for='name'>Name</label>
  <%= f.text_field :campo1, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo2, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo3, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo4, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo5, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo6, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo7, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo8, id: 'name' %>
  <label for='name'>Name</label>
  <%= f.text_field :campo9, id: 'name' %>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>
<%= params %>
<div id="getting-started"></div>

app/views/formularios/formularios_rails.html.erb
<%= form_for(@uno, url: formularios_formularios_rails_path, method: "post") do |f| %>
  <label for='name'>Name</label>
  <%= f.text_field :name, id: 'name' %>
  <label for='age'>Age</label>
  <%= f.text_field :age, id: 'age' %>
  <label form='address'>Address</label>
  <%= f.text_field :address, id: 'address' %>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>
<%= params %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formulario</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post_1s/_form.html.erb
<%= form_for(@post_1) do |f| %>
  <% if @post_1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_1.errors.count, "error") %> prohibited this post_1 from being saved:</h2>

      <ul>
      <% @post_1.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_1s/edit.html.erb
<h1>Editing Post 1</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_1 %> |
<%= link_to 'Back', post_1s_path %>

app/views/post_1s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post 1s</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_1s.each do |post_1| %>
      <tr>
        <td><%= post_1.title %></td>
        <td><%= post_1.content %></td>
        <td><%= post_1.age %></td>
        <td><%= link_to 'Show', post_1 %></td>
        <td><%= link_to 'Edit', edit_post_1_path(post_1) %></td>
        <td><%= link_to 'Destroy', post_1, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post 1', new_post_1_path %>

app/views/post_1s/new.html.erb
<h1>New Post 1</h1>

<%= render 'form' %>

<%= link_to 'Back', post_1s_path %>

app/views/post_1s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post_1.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post_1.content %>
</p>

<p>
  <strong>Age:</strong>
  <%= @post_1.age %>
</p>

<%= link_to 'Edit', edit_post_1_path(@post_1) %> |
<%= link_to 'Back', post_1s_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :agree %><br>
    <%= f.check_box :agree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Age</th>
      <th>Agree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.age %></td>
        <td><%= post.agree %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
<%= params %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Age:</strong>
  <%= @post.age %>
</p>

<p>
  <strong>Agree:</strong>
  <%= @post.agree %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>